
const landingPageStyle = {
 
  appLayoutTrust: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr',
    gridTemplateRows: '45vh',
    position: 'sticky',
    overflowX: 'scroll',
    overflowY: 'hidden',

    marginLeft: '20px',
  },
  photo: {
    marginLeft: '10px',
    width: '50px',
    height: '50px',
    position: 'absolute',
   // border: '1px solid',
    marginTop: '20px',
    borderRadius: '50%',
  },
  rightLink: {
    float: 'right',
    width: '100px',
    height: '36px',
    left: '366px',
    top: '2760px',
    background: '#43BEAC',
    borderRadius: '12px 0px 0px 12px',
    marginTop: '20px',
  },
  rightLinkInfo: {
    position: 'absolute',
    top: '33px',
    height: '16px',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '11px',
    lineHeight: '130%',
    letterSpacing: '0.03em',
    color: '#FFFFFF',
    width: '100px',
  },
  belowText: {
    position: 'absolute',
    height: '69px',
    marginLeft: '10px',
    width: '400px',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '1rem',
    lineHeight: '130%',
    letterSpacing: '0.03em',
    color: '#93A6A3',
    marginTop: '85px',
  },
  picText: {
    position: 'absolute',
    height: '19px',
    marginLeft: '70px',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '1rem',
    lineHeight: '19px',
    letterSpacing: '0.03em',
    marginTop: '30px',
    whiteSpace: 'nowrap',
    color:'white'
  },
  picTextBelow: {
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '12px',
    lineHeight: '14px',
    letterSpacing: '0.03em',
    position: 'absolute',
    marginLeft:'-20px',
    marginBottom:'20px'
  },
  imagetext: {
    fontFamily: 'Futura',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '24px',
    lineHeight: '32px',
    color: '#17212D',
    marginLeft: '100px',
  },
  boxTrust: {
    margin: '10px',
    textAlign: 'center',
    width: '420px',
    height: '197px',
    left: '30px',
    top: '2726px',
    //background: `url(${constants.reviewBackground})`,
    backgroundColor: '#202122',
    borderRadius: '12px',
  },
  belowTextImage: {
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '130%',
    letterSpacing: '0.03em',
    color: '#FFFFFF',
    marginTop: '60px',
    textAlign: 'left',
  },
  boxJoin: {
    margin: '0 auto',
    textAlign: 'center',
    padding: '60px',
    '@media (max-width: 1024px)': {
      padding: '50px',
    },
  },
};

export default landingPageStyle;
